version: '3'

services:
  db:
    image: alpine:latest
    container_name: checktime-db
    volumes:
      - ./db:/data
    command: sh -c "mkdir -p /data && chmod 777 /data && touch /data/checktime.db && chmod 666 /data/checktime.db && tail -f /dev/null"
    restart: unless-stopped

  checktime:
    build: .
    container_name: checktime
    depends_on:
      - db
    environment:
      - CHECKJC_USERNAME=${CHECKJC_USERNAME}
      - CHECKJC_PASSWORD=${CHECKJC_PASSWORD}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - DATABASE_URL=sqlite:////data/checktime.db
      - PORT=5000
      - PYTHONPATH=/app
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
      - ./db:/data
    ports:
      - "5000:5000"
    restart: unless-stopped

  # Separate service for just the checker (optional)
  checktime-checker:
    build: .
    container_name: checktime-checker
    environment:
      - CHECKJC_USERNAME=${CHECKJC_USERNAME}
      - CHECKJC_PASSWORD=${CHECKJC_PASSWORD}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - DATABASE_URL=sqlite:///app/db/checktime.db
      - RUN_MODE=checker_only
      - PYTHONPATH=/app
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
      - database:/app/db
    restart: unless-stopped
    profiles: ["separate"]

  bot:
    build: .
    container_name: checktime-bot
    depends_on:
      - db
    volumes:
      - .:/app
      - /var/log/checktime:/var/log/checktime
      - ./db:/data
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=sqlite:////data/checktime.db
    command: python -m src.checktime.bot.listener
    restart: unless-stopped
    shm_size: '2gb'

  fichar:
    build: .
    container_name: checktime-fichar
    depends_on:
      - db
    volumes:
      - .:/app
      - /var/log/checktime:/var/log/checktime
      - ./db:/data
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=sqlite:////data/checktime.db
    command: python -m src.checktime.main
    restart: unless-stopped
    shm_size: '2gb'

volumes:
  database:
    driver: local 