version: "3.8"

services:
  db:
    image: postgres:15-alpine
    platform: linux/arm64/v8
    container_name: checktime-db
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ${DB_STORAGE_PATH}:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_DB_PORT}:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  app:
    build: .
    container_name: checktime-app
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./config:/app/config
      - /var/log/checktime:/var/log/checktime
    ports:
      - "${WEB_PORT}:${PORT}"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
