name: 🚀 Deploy to Docker VM

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to remote server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        timeout: 60s
        command_timeout: 20m
        proxy_port: 22
        proxy_timeout: 60s
        script: |
          cd ~/apps/CheckTime
          git pull origin main
          docker compose down
          docker compose up -d --build 